config/routes.rb
Askme::Application.routes.draw do
  root to: 'pages#main'
  resources :users
  resources :sessions, only: [:destroy, :create]
  get '/test', to: 'pages#test', as: 'test'
end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  attr_accessible :screen_name, :password_hash, :first_name, :last_name, :email
  include BCrypt

  def password
    @password ||= Password.new(password_hash)
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.password_hash = @password
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
    def check_session
    # if I am coming from "/"
    # binding.pry # pause here
    if request.env["PATH_INFO"] == "/"
      redirect_to test_path if session[:id]
    else
      # if I am on /TEST or any other private page
       if session[:id]
        @user = User.find(session[:id])
      else
        redirect_to root_path

      end
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  before_filter :check_session, except: [:about]
  # this is calling check_session method for all actions except :about

  def about
    # this is a public page for everyone
    # session is not checked here
  end

  def main
    # params
    # request
    binding.pry

    @user = User.new
  end

  def test
    # this is a private page for logged in users
  end



end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    before_filter :check_session, except: []
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
      # as of 06/28/04
      # params = {"user_name"=>"kevin", "password"=>"[FILTERED]"}
      #
      # find the user in db based on their username
      # if your name does not exist redirect
      @user = User.find_by_screen_name(params["user_name"])
      if @user
        if @user.password == params[:password]
          session[:id] = @user.id
          redirect_to test_path
        else
          redirect_to root_path
        end
      else
        redirect_to root_path
      end
      # check password
      # if success
      # save user_id to sessions hash
      # if failure redirect
  end

  def destroy
    reset_session
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new

  end
  def create
    @user = User.new(screen_name: params["user"]["screen_name"],
                     first_name: params["user"]["first_name"],
                     last_name: params["user"]["last_name"],
                     email: params["user"]["email"])
    @user.password=(params['user']['password'])
    @user.save
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/pages_helper.rb
module PagesHelper

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Askme</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<h1>Hello I am creator</h1>

app/views/pages/main.html.erb
<h1>Ask Me!</h1>
<a href="/about">about page</a>
<!-- pass @user to the partial -->
<%= render :partial => "/users/signup_form", :locals => {:user => @user} %>

<%= render :partial => "/sessions/sign_in", :locals => {:user => @user} %>

app/views/pages/test.html.erb
<p>success!</p>

<%= button_to("log out", session_path(session[:id]),method: :delete) %>

app/views/users/_signup_form.html.erb
<div id="signUpForm">
  <%# form_for :user,  url: users_path do |user_form| %>

  <!-- we passed @users as a local from the main.html.erb file which originated from the controller -->
  <%= form_for @user do |user_form| %>
    <%= user_form.text_field :screen_name , :placeholder => "screen name"%>
    <%= user_form.password_field :password , :placeholder => "password"%>
    <%= user_form.text_field :first_name , :placeholder => "first name"%>
    <%= user_form.text_field :last_name , :placeholder => "last name"%>
    <%= user_form.email_field :email , :placeholder => "email"%>
    <%= user_form.submit %>
  <% end %>
</div>